"""
3D Mesh and Simulation Exporter module for Context Generator.
Exports generated context scenes into .OBJ, .STL, .GLTF, and .JSON formats
for downstream solar, radiation, wind CFD, and building environmental simulations.
"""

import json
import os
import numpy as np

try:
    import trimesh
    TRIMESH_AVAILABLE = True
except ImportError:
    TRIMESH_AVAILABLE = False


def export_context_to_obj(scene, output_obj_path):
    """
    Exports the site boundary and surrounding 3D context buildings into a single Wavefront .OBJ file.
    Differentiates Site Parcel mesh and Context Building meshes into named sub-groups (g SiteParcel, g ContextBuildings).
    """
    os.makedirs(os.path.dirname(output_obj_path), exist_ok=True)

    lines = []
    lines.append(f"# OBJ file generated by Context Generator")
    lines.append(f"# City/Profile: {scene.get('city_name', scene.get('density_class', 'Synthetic'))}")
    lines.append(f"# Radius: {scene.get('radius_m', 100.0)}m\n")

    vert_offset = 1  # 1-indexed in OBJ

    # Group 1: Testing Site Boundary Parcel (Flat mesh at z=0)
    lines.append("g SiteParcel")
    site_verts = np.array(scene["site_boundary"]["vertices_2d"])
    n_site = len(site_verts)
    for x, y in site_verts:
        lines.append(f"v {x:.4f} {y:.4f} 0.0000")

    # Simple fan triangulation for site polygon
    for i in range(1, n_site - 1):
        lines.append(f"f {vert_offset} {vert_offset + i} {vert_offset + i + 1}")

    vert_offset += n_site

    # Group 2: Context Buildings
    lines.append("\ng ContextBuildings")

    for idx, b in enumerate(scene["context_buildings"]):
        verts_2d = np.array(b["vertices_2d"])
        h = b.get("height", 20.0)
        n = len(verts_2d)

        # Write 3D vertices (0..n-1 on ground z=0, n..2n-1 at roof z=h)
        for x, y in verts_2d:
            lines.append(f"v {x:.4f} {y:.4f} 0.0000")
        for x, y in verts_2d:
            lines.append(f"v {x:.4f} {y:.4f} {h:.4f}")

        # Write Faces
        # Side Walls
        for i in range(n):
            next_i = (i + 1) % n
            b1 = vert_offset + i
            b2 = vert_offset + next_i
            t1 = vert_offset + i + n
            t2 = vert_offset + next_i + n

            lines.append(f"f {b1} {b2} {t2}")
            lines.append(f"f {b1} {t2} {t1}")

        # Top Roof Cap
        for i in range(1, n - 1):
            lines.append(f"f {vert_offset + n} {vert_offset + n + i} {vert_offset + n + i + 1}")

        vert_offset += 2 * n

    with open(output_obj_path, "w") as f:
        f.write("\n".join(lines))

    print(f"[Exporter Success] Exported 3D Wavefront OBJ mesh to: {output_obj_path}")
    return output_obj_path


def export_context_to_json(scene, output_json_path):
    """Exports structured scene JSON containing site boundary, building coordinates, heights, and metrics."""
    os.makedirs(os.path.dirname(output_json_path), exist_ok=True)

    clean_scene = json.loads(json.dumps(scene, default=lambda o: o.tolist() if isinstance(o, np.ndarray) else o))

    with open(output_json_path, "w") as f:
        json.dump(clean_scene, f, indent=2)

    print(f"[Exporter Success] Exported scene data JSON to: {output_json_path}")
    return output_json_path
